version: '3'
services:

  balancer:
    build:
      dockerfile: Dockerfile
      context: .
    command: "python /app/src/server.py"
    entrypoint: ""
    depends_on:
      - redis
    restart: "no"
    volumes:
      - .:/app
    environment:
      # App server settings
      - PYTHONPATH=/app
      - ENTRYPOINT_NOWAIT=1
      - PORT=8000
      - DEBUG=True
      - WORKERS=1
      - REDIS_ENDPOINT=redis
      - REDIS_DB=1
      - REDIS_PREFIX=load_balancer
      # App logic settings
      - ORIGINAL_LINK_FREQUENCY=10
      - CDN_HOST=www.awesome-cdn.ru
    ports:
    - "8000:8000"

  balancer_test:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis_test
    restart: "no"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - ENTRYPOINT_NOWAIT=1
      - REDIS_ENDPOINT=redis_test
      - REDIS_DB=1
      - REDIS_PREFIX=load_balancer
      # App logic settings
      - ORIGINAL_LINK_FREQUENCY=3
      - CDN_HOST=www.awesome-cdn.ru
    tty: true

  redis:
    image: redis:6.2.6-alpine
    command: redis-server --maxmemory 64Mb
    restart: "no"

  redis_test:
    image: redis:6.2.6-alpine
    command: redis-server --maxmemory 64Mb
    restart: "no"

volumes:
  data:
